//
//  Colors.swift
//  DoctoApp
//
//  Created by LAVIOLETTE JOACHIM on 03/12/2019.
//  Copyright © 2019 LAVIOLETTE JOACHIM. All rights reserved.
//

import UIKit

struct Colors {
    // Main
    public static let MAIN_BACKGROUND: String = "#83BFD7"
    public static let MAIN_LOGO: String = "#FFFFFF"
    public static let MAIN_CAPTION: String = "#FFFFFF"
    public static let MAIN_SEARCH_BAR_TEXT: String = "#858585"
    public static let MAIN_SEARCH_BAR_HINT: String = "#D8D8D8"
    public static let MAIN_SEARCH_BTN_BACKGROUND: String = "#FF7509"
    public static let MAIN_SEARCH_BTN_TEXT: String = "#FFFFFF"

    // Login
    public static let LOGIN_BACKGROUND: String = "#E4E4E4"
    public static let LOGIN_CAPTION: String = "#696969"
    public static let LOGIN_INPUT_TEXT: String = "#858585"
    public static let LOGIN_INPUT_HINT: String = "#D8D8D8"
    public static let LOGIN_FORGOT_PWD: String = "#1B86E4"
    public static let LOGIN_BTN_BACKGROUND: String = "#1B86E4"
    public static let LOGIN_BTN_TEXT: String = "#FFFFFF"
    public static let LOGIN_MY_PROFILE_BTN_BACKGROUND: String = "#1B86E4"
    public static let LOGIN_MY_PROFILE_BTN_TEXT: String = "#FFFFFF"
    public static let LOGIN_MY_BOOKINGS_BTN_BACKGROUND: String = "#1B86E4"
    public static let LOGIN_MY_BOOKINGS_BTN_TEXT: String = "#FFFFFF"
    public static let LOGIN_DELETE_ACCOUNT_BTN_BACKGROUND: String = "#1B86E4"
    public static let LOGIN_DELETE_ACCOUNT_BTN_TEXT: String = "#FFFFFF"
    public static let LOGIN_LOGOUT_BTN_BACKGROUND: String = "#BE4A4A"
    public static let LOGIN_LOGOUT_BTN_TEXT: String = "#FFFFFF"
    public static let LOGIN_STAY_LOGGED: String = "#858585"
    public static let LOGIN_SIGNUP_BACKGROUND: String = "#FFFFFF"
    public static let LOGIN_SIGNUP_CAPTION: String = "#252525"
    public static let LOGIN_SIGNUP_LINK: String = "#1B86E4"
    public static let LOGIN_SIGNUP_PRO_BACKGROUND: String = "#FFFFFF"
    public static let LOGIN_SIGNUP_PRO_CAPTION: String = "#252525"
    public static let LOGIN_SIGNUP_PRO_LINK: String = "#1B86E4"
    public static let LOGIN_SUCCESS_MSG: String = "#18965A"
    public static let LOGIN_ERROR_MSG: String = "#BE4A4A"
    public static let LOGIN_SUCCESS_MSG_TITLE: String = "#FFFFFF"
    public static let LOGIN_SUCCESS_MSG_CONTENT: String = "#FFFFFF"
    public static let LOGIN_DELETE_ACCOUNT_MSG: String = "#BE4A4A"
    public static let LOGIN_DELETE_ACCOUNT_MSG_TITLE: String = "#FFFFFF"
    public static let LOGIN_DELETE_ACCOUNT_MSG_CONTENT: String = "#FFFFFF"
    public static let LOGIN_DELETE_ACCOUNT_POPUP_EXTERNAL_BACKGROUND: String = "#000000"
    public static let LOGIN_DELETE_ACCOUNT_POPUP_BACKGROUND: String = "#FFFFFF"
    public static let LOGIN_DELETE_ACCOUNT_POPUP_TITLE: String = "#FFFFFF"
    public static let LOGIN_DELETE_ACCOUNT_POPUP_TITLE_BACKGROUND: String = "#1B86E4"
    public static let LOGIN_DELETE_ACCOUNT_POPUP_SECTION_TITLE: String = "#444444"
    public static let LOGIN_DELETE_ACCOUNT_POPUP_SECTION_CONTENT: String = "#727272"
    public static let LOGIN_DELETE_ACCOUNT_POPUP_CLOSE: String = "#FFFFFF"
    public static let LOGIN_DELETE_ACCOUNT_POPUP_BTN_TEXT: String = "#FFFFFF"

    // Forgot password
    public static let FORGOT_PASSWORD_BACKGROUND: String = "#E4E4E4"
    public static let FORGOT_PASSWORD_CAPTION: String = "#696969"
    public static let FORGOT_PASSWORD_INPUT_TEXT: String = "#858585"
    public static let FORGOT_PASSWORD_INPUT_HINT: String = "#D8D8D8"
    public static let FORGOT_PASSWORD_FORGOT_PWD: String = "#1B86E4"
    public static let FORGOT_PASSWORD_BTN_BACKGROUND: String = "#1B86E4"
    public static let FORGOT_PASSWORD_BTN_TEXT: String = "#FFFFFF"
    public static let FORGOT_PASSWORD_SUCCESS_MSG: String = "#18965A"
    public static let FORGOT_PASSWORD_ERROR_MSG: String = "#BE4A4A"
    public static let FORGOT_PASSWORD_PASSWORD_UPDATED_MSG_TITLE: String = "#FFFFFF"
    public static let FORGOT_PASSWORD_PASSWORD_UPDATED_MSG_CONTENT: String = "#FFFFFF"

    // Signup
    public static let SIGNUP_BACKGROUND: String = "#E4E4E4"
    public static let SIGNUP_CAPTION: String = "#696969"
    public static let SIGNUP_SECTION_LABEL: String = "#696969"
    public static let SIGNUP_INPUT_TEXT: String = "#858585"
    public static let SIGNUP_INPUT_HINT: String = "#D8D8D8"
    public static let SIGNUP_BTN_BACKGROUND: String = "#1B86E4"
    public static let SIGNUP_BTN_TEXT: String = "#FFFFFF"
    public static let SIGNUP_LOGIN_BACKGROUND: String = "#FFFFFF"
    public static let SIGNUP_LOGIN_LINK: String = "#1B86E4"
    public static let SIGNUP_PRO_ACCOUNT_BACKGROUND: String = "#FFFFFF"
    public static let SIGNUP_PRO_ACCOUNT_LINK: String = "#1B86E4"
    public static let SIGNUP_SUCCESS_MSG: String = "#18965A"
    public static let SIGNUP_ERROR_MSG: String = "#BE4A4A"
    public static let SIGNUP_SUCCESS_MSG_TITLE: String = "#FFFFFF"
    public static let SIGNUP_SUCCESS_MSG_CONTENT: String = "#FFFFFF"
    public static let SIGNUP_TAKE_PICTURE_FROM_CAMERA: String = "#494949"
    public static let SIGNUP_TAKE_PICTURE_FROM_CAMERA_TEXT: String = "#FFFFFF"
    public static let SIGNUP_SELECT_PICTURE_FROM_GALLERY: String = "#494949"
    public static let SIGNUP_SELECT_PICTURE_FROM_GALLERY_TEXT: String = "#FFFFFF"

    // My profile
    public static let MY_PROFILE_BACKGROUND: String = "#E4E4E4"
    public static let MY_PROFILE_CAPTION: String = "#696969"
    public static let MY_PROFILE_SECTION_LABEL: String = "#696969"
    public static let MY_PROFILE_INPUT_TEXT: String = "#858585"
    public static let MY_PROFILE_INPUT_HINT: String = "#D8D8D8"
    public static let MY_PROFILE_UPDATE_BTN_BACKGROUND: String = "#1B86E4"
    public static let MY_PROFILE_UPDATE_BTN_TEXT: String = "#FFFFFF"
    public static let MY_PROFILE_LOGIN_BACKGROUND: String = "#FFFFFF"
    public static let MY_PROFILE_LOGIN_LINK: String = "#1B86E4"
    public static let MY_PROFILE_PRO_ACCOUNT_BACKGROUND: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_ACCOUNT_LINK: String = "#1B86E4"
    public static let MY_PROFILE_SUCCESS_MSG: String = "#18965A"
    public static let MY_PROFILE_ERROR_MSG: String = "#BE4A4A"
    public static let MY_PROFILE_SUCCESS_MSG_TITLE: String = "#FFFFFF"
    public static let MY_PROFILE_SUCCESS_MSG_CONTENT: String = "#FFFFFF"
    public static let MY_PROFILE_TAKE_PICTURE_FROM_CAMERA: String = "#494949"
    public static let MY_PROFILE_TAKE_PICTURE_FROM_CAMERA_TEXT: String = "#FFFFFF"
    public static let MY_PROFILE_SELECT_PICTURE_FROM_GALLERY: String = "#494949"
    public static let MY_PROFILE_SELECT_PICTURE_FROM_GALLERY_TEXT: String = "#FFFFFF"

    // Signup pro
    public static let SIGNUP_PRO_BACKGROUND: String = "#E4E4E4"
    public static let SIGNUP_PRO_CAPTION: String = "#696969"
    public static let SIGNUP_PRO_SECTION_LABEL: String = "#696969"
    public static let SIGNUP_PRO_INPUT_TEXT: String = "#858585"
    public static let SIGNUP_PRO_INPUT_HINT: String = "#D8D8D8"
    public static let SIGNUP_PRO_BTN_BACKGROUND: String = "#1B86E4"
    public static let SIGNUP_PRO_BTN_TEXT: String = "#FFFFFF"
    public static let SIGNUP_PRO_LOGIN_BACKGROUND: String = "#FFFFFF"
    public static let SIGNUP_PRO_LOGIN_LINK: String = "#1B86E4"
    public static let SIGNUP_PRO_PRIVATE_ACCOUNT_BACKGROUND: String = "#FFFFFF"
    public static let SIGNUP_PRO_PRIVATE_ACCOUNT_LINK: String = "#1B86E4"
    public static let SIGNUP_PRO_SUCCESS_MSG: String = "#18965A"
    public static let SIGNUP_PRO_SUCCESS_MSG_TITLE: String = "#FFFFFF"
    public static let SIGNUP_PRO_SUCCESS_MSG_CONTENT: String = "#FFFFFF"
    public static let SIGNUP_PRO_TAKE_PICTURE_FROM_CAMERA: String = "#494949"
    public static let SIGNUP_PRO_TAKE_PICTURE_FROM_CAMERA_TEXT: String = "#FFFFFF"
    public static let SIGNUP_PRO_SELECT_PICTURE_FROM_GALLERY: String = "#494949"
    public static let SIGNUP_PRO_SELECT_PICTURE_FROM_GALLERY_TEXT: String = "#FFFFFF"
    public static let SIGNUP_PRO_TAKE_HEADER_FROM_CAMERA: String = "#494949"
    public static let SIGNUP_PRO_TAKE_HEADER_FROM_CAMERA_TEXT: String = "#FFFFFF"
    public static let SIGNUP_PRO_SELECT_HEADER_FROM_GALLERY: String = "#494949"
    public static let SIGNUP_PRO_SELECT_HEADER_FROM_GALLERY_TEXT: String = "#FFFFFF"
    public static let SIGNUP_PRO_OPTION: String = "#858585"
    public static let SIGNUP_PRO_OPTION_SELECTED: String = "#1B86E4"
    public static let SIGNUP_PRO_SECTION: String = "#FFFFFF"
    public static let SIGNUP_PRO_ADD_AVAILABILITY_BTN: String = "#1B86E4"
    public static let SIGNUP_PRO_ADD_REASON_BTN: String = "#1B86E4"
    public static let SIGNUP_PRO_ADD_TRAINING_BTN: String = "#1B86E4"
    public static let SIGNUP_PRO_ADD_EXPERIENCE_BTN: String = "#1B86E4"
    public static let SIGNUP_PRO_ADD_LANGUAGE_BTN: String = "#1B86E4"
    public static let SIGNUP_PRO_ADD_PAYMENT_OPTION_BTN: String = "#1B86E4"
    public static let SIGNUP_PRO_ADD_AVAILABILITY_BTN_TEXT: String = "#FFFFFF"
    public static let SIGNUP_PRO_ADD_REASON_BTN_TEXT: String = "#FFFFFF"
    public static let SIGNUP_PRO_ADD_TRAINING_BTN_TEXT: String = "#FFFFFF"
    public static let SIGNUP_PRO_ADD_EXPERIENCE_BTN_TEXT: String = "#FFFFFF"
    public static let SIGNUP_PRO_ADD_LANGUAGE_BTN_TEXT: String = "#FFFFFF"
    public static let SIGNUP_PRO_ADD_PAYMENT_OPTION_BTN_TEXT: String = "#FFFFFF"
    public static let SIGNUP_PRO_DAYS_LIST: String = "#F8F8F8"
    public static let SIGNUP_PRO_LANGUAGES_LIST: String = "#F8F8F8"
    public static let SIGNUP_PRO_PAYMENT_OPTIONS_LIST: String = "#F8F8F8"
    public static let SIGNUP_PRO_INFO_MSG: String = "#3081C7"
    public static let SIGNUP_PRO_INFO_MSG_BACKGROUND: String = "#EDF2F5"
    public static let SIGNUP_PRO_ERROR_MSG: String = "#BE4A4A"
    public static let SIGNUP_PRO_ERROR_MSG_BACKGROUND: String = "#ECDEDE"

    // Signup list item
    public static let SIGNUP_PRO_LIST_ITEM_REMOVE: String = "#BE4A4A"
    public static let SIGNUP_PRO_LIST_ITEM_PIPE: String = "#696969"

    // Availability signup list item
    public static let AVAILABILITY_SIGNUP_PRO_LIST_ITEM_DAY: String = "#696969"
    public static let AVAILABILITY_SIGNUP_PRO_LIST_ITEM_TIME: String = "#B3B3B3"

    // Reason signup list item
    public static let REASON_SIGNUP_PRO_LIST_ITEM_DESCRIPTION: String = "#696969"

    // Education signup list item
    public static let EDUCATION_SIGNUP_PRO_LIST_ITEM_YEAR: String = "#696969"
    public static let EDUCATION_SIGNUP_PRO_LIST_ITEM_DEGREE: String = "#B3B3B3"

    // Experience signup list item
    public static let EXPERIENCE_SIGNUP_PRO_LIST_ITEM_YEAR: String = "#696969"
    public static let EXPERIENCE_SIGNUP_PRO_LIST_ITEM_DESCRIPTION: String = "#B3B3B3"

    // Language signup list item
    public static let LANGUAGE_SIGNUP_PRO_LIST_ITEM_DESCRIPTION: String = "#696969"

    // Payment option signup list item
    public static let PAYMENT_OPTION_SIGNUP_PRO_LIST_ITEM_DESCRIPTION: String = "#696969"

    // My profile pro
    public static let MY_PROFILE_PRO_BACKGROUND: String = "#E4E4E4"
    public static let MY_PROFILE_PRO_CAPTION: String = "#696969"
    public static let MY_PROFILE_PRO_SECTION_LABEL: String = "#696969"
    public static let MY_PROFILE_PRO_INPUT_TEXT: String = "#858585"
    public static let MY_PROFILE_PRO_INPUT_HINT: String = "#D8D8D8"
    public static let MY_PROFILE_PRO_BTN_BACKGROUND: String = "#1B86E4"
    public static let MY_PROFILE_PRO_BTN_TEXT: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_LOGIN_BACKGROUND: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_LOGIN_LINK: String = "#1B86E4"
    public static let MY_PROFILE_PRO_PRIVATE_ACCOUNT_BACKGROUND: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_PRIVATE_ACCOUNT_LINK: String = "#1B86E4"
    public static let MY_PROFILE_PRO_SUCCESS_MSG: String = "#18965A"
    public static let MY_PROFILE_PRO_SUCCESS_MSG_TITLE: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_SUCCESS_MSG_CONTENT: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_TAKE_PICTURE_FROM_CAMERA: String = "#494949"
    public static let MY_PROFILE_PRO_TAKE_PICTURE_FROM_CAMERA_TEXT: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_SELECT_PICTURE_FROM_GALLERY: String = "#494949"
    public static let MY_PROFILE_PRO_SELECT_PICTURE_FROM_GALLERY_TEXT: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_TAKE_HEADER_FROM_CAMERA: String = "#494949"
    public static let MY_PROFILE_PRO_TAKE_HEADER_FROM_CAMERA_TEXT: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_SELECT_HEADER_FROM_GALLERY: String = "#494949"
    public static let MY_PROFILE_PRO_SELECT_HEADER_FROM_GALLERY_TEXT: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_OPTION: String = "#858585"
    public static let MY_PROFILE_PRO_OPTION_SELECTED: String = "#1B86E4"
    public static let MY_PROFILE_PRO_SECTION: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_ADD_AVAILABILITY_BTN: String = "#1B86E4"
    public static let MY_PROFILE_PRO_ADD_REASON_BTN: String = "#1B86E4"
    public static let MY_PROFILE_PRO_ADD_TRAINING_BTN: String = "#1B86E4"
    public static let MY_PROFILE_PRO_ADD_EXPERIENCE_BTN: String = "#1B86E4"
    public static let MY_PROFILE_PRO_ADD_LANGUAGE_BTN: String = "#1B86E4"
    public static let MY_PROFILE_PRO_ADD_PAYMENT_OPTION_BTN: String = "#1B86E4"
    public static let MY_PROFILE_PRO_ADD_AVAILABILITY_BTN_TEXT: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_ADD_REASON_BTN_TEXT: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_ADD_TRAINING_BTN_TEXT: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_ADD_EXPERIENCE_BTN_TEXT: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_ADD_LANGUAGE_BTN_TEXT: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_ADD_PAYMENT_OPTION_BTN_TEXT: String = "#FFFFFF"
    public static let MY_PROFILE_PRO_DAYS_LIST: String = "#F8F8F8"
    public static let MY_PROFILE_PRO_LANGUAGES_LIST: String = "#F8F8F8"
    public static let MY_PROFILE_PRO_PAYMENT_OPTIONS_LIST: String = "#F8F8F8"
    public static let MY_PROFILE_PRO_INFO_MSG: String = "#3081C7"
    public static let MY_PROFILE_PRO_INFO_MSG_BACKGROUND: String = "#EDF2F5"
    public static let MY_PROFILE_PRO_ERROR_MSG: String = "#BE4A4A"
    public static let MY_PROFILE_PRO_ERROR_MSG_BACKGROUND: String = "#ECDEDE"

    // My profile pro list item
    public static let MY_PROFILE_PRO_LIST_ITEM_REMOVE: String = "#BE4A4A"
    public static let MY_PROFILE_PRO_LIST_ITEM_PIPE: String = "#696969"

    // Availability my profile pro list item
    public static let AVAILABILITY_MY_PROFILE_PRO_LIST_ITEM_DAY: String = "#696969"
    public static let AVAILABILITY_MY_PROFILE_PRO_LIST_ITEM_TIME: String = "#B3B3B3"

    // Reason my profile pro list item
    public static let REASON_MY_PROFILE_PRO_LIST_ITEM_DESCRIPTION: String = "#696969"

    // Education my profile pro list item
    public static let EDUCATION_MY_PROFILE_PRO_LIST_ITEM_YEAR: String = "#696969"
    public static let EDUCATION_MY_PROFILE_PRO_LIST_ITEM_DEGREE: String = "#B3B3B3"

    // Experience my profile pro list item
    public static let EXPERIENCE_MY_PROFILE_PRO_LIST_ITEM_YEAR: String = "#696969"
    public static let EXPERIENCE_MY_PROFILE_PRO_LIST_ITEM_DESCRIPTION: String = "#B3B3B3"

    // Language my profile pro list item
    public static let LANGUAGE_MY_PROFILE_PRO_LIST_ITEM_DESCRIPTION: String = "#696969"

    // Payment option my profile pro list item
    public static let PAYMENT_OPTION_MY_PROFILE_PRO_LIST_ITEM_DESCRIPTION: String = "#696969"

    // Search
    public static let SEARCH_BACKGROUND: String = "#FFFFFF"
    public static let SEARCH_BAR_TEXT: String = "#858585"
    public static let SEARCH_BAR_HINT: String = "#D8D8D8"
    public static let SEARCH_BAR_SHADOW: String = "#1D1D1D"
    public static let SEARCH_BTN_BACKGROUND: String = "#444444"
    public static let SEARCH_BTN_TEXT: String = "#FFFFFF"

    // Search list
    public static let SEARCH_LIST_BACKGROUND: String = "#FFFFFF"
    public static let SEARCH_LIST_DIVIDER: String = "#D5D5D5"
    public static let SEARCH_LIST_ITEM_DOCTOR_FULLNAME: String = "#1B86E4"
    public static let SEARCH_LIST_ITEM_DOCTOR_SPECIALITY: String = "#696969"
    public static let SEARCH_LIST_ITEM_DOCTOR_ADDRESS: String = "#696969"
    public static let SEARCH_LIST_ITEM_CHEVRON: String = "#E9E9E9"

    // Doctor profile
    public static let DOCTOR_PROFILE_BACKGROUND: String = "#E4E4E4"
    public static let DOCTOR_PROFILE_FULLNAME: String = "#FFFFFF"
    public static let DOCTOR_PROFILE_SPECIALITY: String = "#FFFFFF"
    public static let DOCTOR_PROFILE_BOOK_APPOINTMENT_BTN: String = "#1B86E4"
    public static let DOCTOR_PROFILE_BOOK_APPOINTMENT_TEXT: String = "#FFFFFF"
    public static let DOCTOR_PROFILE_SECTION_BACKGROUND: String = "#FFFFFF"
    public static let DOCTOR_PROFILE_SECTION_TITLE: String = "#444444"
    public static let DOCTOR_PROFILE_SECTION_CONTENT: String = "#727272"
    public static let DOCTOR_PROFILE_SECTION_CONTENT_BACKGROUND: String = "#B8B8B8"
    public static let DOCTOR_PROFILE_SECTION_EXPAND: String = "#E9E9E9"
    public static let DOCTOR_PROFILE_UNAVAILABLE: String = "#BE4A4A"
    public static let DOCTOR_PROFILE_POPUP_EXTERNAL_BACKGROUND: String = "#000000"
    public static let DOCTOR_PROFILE_POPUP_BACKGROUND: String = "#FFFFFF"
    public static let DOCTOR_PROFILE_POPUP_TITLE: String = "#FFFFFF"
    public static let DOCTOR_PROFILE_POPUP_TITLE_BACKGROUND: String = "#1B86E4"
    public static let DOCTOR_PROFILE_POPUP_SECTION_TITLE: String = "#444444"
    public static let DOCTOR_PROFILE_POPUP_SECTION_CONTENT: String = "#727272"
    public static let DOCTOR_PROFILE_POPUP_CLOSE: String = "#FFFFFF"
    public static let DOCTOR_PROFILE_SHADOW: String = "#222222"

    // Choose reason
    public static let CHOOSE_REASON_HEADER: String = "#1B86E4"
    public static let CHOOSE_REASON_BODY: String = "#E4E4E4"
    public static let CHOOSE_REASON_TITLE_1: String = "#66A8E2"
    public static let CHOOSE_REASON_DOCTOR_FULLNAME: String = "#FFFFFF"
    public static let CHOOSE_REASON_TITLE_2: String = "#444444"

    // Reason list
    public static let REASON_LIST: String = "#FFFFFF"
    public static let REASON_LIST_ITEM_REASON: String = "#444444"
    public static let REASON_LIST_DIVIDER: String = "#E4E4E4"

    // Choose datetime
    public static let CHOOSE_DATE_TIME_HEADER: String = "#1B86E4"
    public static let CHOOSE_DATE_TIME_BODY: String = "#E4E4E4"
    public static let CHOOSE_DATE_TIME_TITLE_1: String = "#66A8E2"
    public static let CHOOSE_DATE_TIME_DOCTOR_FULLNAME: String = "#FFFFFF"
    public static let CHOOSE_DATE_TIME_TITLE_2: String = "#444444"

    // Datetime list
    public static let DATE_TIME_DATETIME_LAYOUT: String = "#FFFFFF"
    public static let DATE_TIME_DAY: String = "#444444"
    public static let DATE_TIME_TIME: String = "#444444"
    public static let DATE_TIME_TIME_BACKGROUND: String = "#FAFAFA"
    public static let DATE_TIME_LIST_DIVIDER: String = "#E4E4E4"

    // Confirm appointment
    public static let CONFIRM_APPOINTMENT_HEADER: String = "#1B86E4"
    public static let CONFIRM_APPOINTMENT_HEADER_TITLE: String = "#FFFFFF"
    public static let CONFIRM_APPOINTMENT_BODY: String = "#E4E4E4"
    public static let CONFIRM_APPOINTMENT_SUCCESS_MSG: String = "#18965A"
    public static let CONFIRM_APPOINTMENT_ERROR_MSG: String = "#BE4A4A"
    public static let CONFIRM_APPOINTMENT_SUCCESS_MSG_TITLE: String = "#FFFFFF"
    public static let CONFIRM_APPOINTMENT_SUCCESS_MSG_CONTENT: String = "#FFFFFF"
    public static let CONFIRM_APPOINTMENT_MY_BOOKINGS_BACKGROUND: String = "#7A4ABE"
    public static let CONFIRM_APPOINTMENT_MY_BOOKINGS_TEXT: String = "#FFFFFF"

    // Appointment summary
    public static let APPOINTMENT_SUMMARY_HEADER: String = "#444444"
    public static let APPOINTMENT_SUMMARY_BODY: String = "#FFFFFF"
    public static let APPOINTMENT_SUMMARY_FULLDAY: String = "#FFFFFF"
    public static let APPOINTMENT_SUMMARY_TIME: String = "#FFFFFF"
    public static let APPOINTMENT_SUMMARY_DOCTOR_FULLNAME: String = "#444444"
    public static let APPOINTMENT_SUMMARY_DOCTOR_SPECIALITY: String = "#727272"
    public static let APPOINTMENT_SUMMARY_REASON: String = "#BE4A4A"
    public static let APPOINTMENT_SUMMARY_CHEVRON: String = "#E9E9E9"
    public static let APPOINTMENT_SUMMARY_PATIENT_TITLE: String = "#444444"
    public static let APPOINTMENT_SUMMARY_PATIENT_FULLNAME: String = "#727272"
    public static let APPOINTMENT_SUMMARY_WARNING_MSG_TITLE: String = "#444444"
    public static let APPOINTMENT_SUMMARY_WARNING_MSG_CONTENT: String = "#727272"
    public static let APPOINTMENT_SUMMARY_CONTACT_NUMBER: String = "#1B86E4"
    public static let APPOINTMENT_SUMMARY_ADDRESS_CONTENT: String = "#1B86E4"
    public static let APPOINTMENT_SUMMARY_PAYMENT_OPTIONS_TITLE: String = "#444444"
    public static let APPOINTMENT_SUMMARY_PAYMENT_OPTIONS_CONTENT: String = "#727272"
    public static let APPOINTMENT_SUMMARY_PRICES_REFUNDS_TITLE: String = "#444444"
    public static let APPOINTMENT_SUMMARY_PRICES_REFUNDS_CONTENT: String = "#727272"
    public static let APPOINTMENT_SUMMARY_ICON_TINT: String = "#DBDBDB"

    // Patient appointment item
    public static let PATIENT_APPOINTMENT_ITEM_HEADER: String = "#444444"
    public static let PATIENT_APPOINTMENT_ITEM_BODY: String = "#FFFFFF"
    public static let PATIENT_APPOINTMENT_ITEM_FULLDAY: String = "#FFFFFF"
    public static let PATIENT_APPOINTMENT_ITEM_TIME: String = "#FFFFFF"
    public static let PATIENT_APPOINTMENT_ITEM_DOCTOR_FULLNAME: String = "#444444"
    public static let PATIENT_APPOINTMENT_ITEM_DOCTOR_SPECIALITY: String = "#727272"
    public static let PATIENT_APPOINTMENT_ITEM_CHEVRON: String = "#E9E9E9"

    // Show booking
    public static let SHOW_BOOKING_LAYOUT: String = "#E4E4E4"
    public static let SHOW_BOOKING_HEADER: String = "#1B86E4"
    public static let SHOW_BOOKING_TITLE: String = "#66A8E2"
    public static let SHOW_BOOKING_SUBTITLE: String = "#FFFFFF"
    public static let SHOW_BOOKING_APPOINTMENT_HEADER: String = "#444444"
    public static let SHOW_BOOKING_APPOINTMENT_BODY: String = "#FFFFFF"
    public static let SHOW_BOOKING_APPOINTMENT_FULLDAY: String = "#FFFFFF"
    public static let SHOW_BOOKING_APPOINTMENT_TIME: String = "#FFFFFF"
    public static let SHOW_BOOKING_APPOINTMENT_DOCTOR_FULLNAME: String = "#444444"
    public static let SHOW_BOOKING_APPOINTMENT_DOCTOR_SPECIALITY: String = "#727272"
    public static let SHOW_BOOKING_APPOINTMENT_PATIENT_FULLNAME: String = "#444444"
    public static let SHOW_BOOKING_APPOINTMENT_PATIENT_BIRTHDATE: String = "#727272"
    public static let SHOW_BOOKING_APPOINTMENT_UPDATE_APPOINTMENT: String = "#1B86E4"
    public static let SHOW_BOOKING_APPOINTMENT_UPDATE_APPOINTMENT_BACKGROUND: String = "#ECF1F5"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT: String = "#BE4A4A"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_BACKGROUND: String = "#F5ECEC"
    public static let SHOW_BOOKING_APPOINTMENT_CHEVRON: String = "#E9E9E9"
    public static let SHOW_BOOKING_APPOINTMENT_WARNING_MSG_TITLE: String = "#444444"
    public static let SHOW_BOOKING_APPOINTMENT_WARNING_MSG_CONTENT: String = "#727272"
    public static let SHOW_BOOKING_APPOINTMENT_CONTACT_NUMBER: String = "#1B86E4"
    public static let SHOW_BOOKING_APPOINTMENT_ADDRESS_CONTENT: String = "#1B86E4"
    public static let SHOW_BOOKING_APPOINTMENT_PAYMENT_OPTIONS_TITLE: String = "#444444"
    public static let SHOW_BOOKING_APPOINTMENT_PAYMENT_OPTIONS_CONTENT: String = "#727272"
    public static let SHOW_BOOKING_APPOINTMENT_PRICES_REFUNDS_TITLE: String = "#444444"
    public static let SHOW_BOOKING_APPOINTMENT_PRICES_REFUNDS_CONTENT: String = "#727272"
    public static let SHOW_BOOKING_APPOINTMENT_REASON: String = "#BE4A4A"
    public static let SHOW_BOOKING_APPOINTMENT_ICON_TINT: String = "#DBDBDB"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_MSG: String = "#BE4A4A"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_MSG_TITLE: String = "#FFFFFF"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_MSG_CONTENT: String = "#FFFFFF"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_MSG_CONTENT_DETAILS: String = "#1B86E4"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_EXTERNAL_BACKGROUND: String = "#000000"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_BACKGROUND: String = "#FFFFFF"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_TITLE: String = "#FFFFFF"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_TITLE_BACKGROUND: String = "#1B86E4"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_SECTION_TITLE: String = "#444444"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_SECTION_CONTENT: String = "#727272"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_CLOSE: String = "#FFFFFF"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_BTN_TEXT: String = "#FFFFFF"

    // Doctor appointment item
    public static let DOCTOR_APPOINTMENT_ITEM_HEADER: String = "#444444"
    public static let DOCTOR_APPOINTMENT_ITEM_BODY: String = "#FFFFFF"
    public static let DOCTOR_APPOINTMENT_ITEM_FULLDAY: String = "#FFFFFF"
    public static let DOCTOR_APPOINTMENT_ITEM_TIME: String = "#FFFFFF"
    public static let DOCTOR_APPOINTMENT_ITEM_PATIENT_FULLNAME: String = "#444444"
    public static let DOCTOR_APPOINTMENT_ITEM_PATIENT_BIRTHDATE: String = "#727272"
    public static let DOCTOR_APPOINTMENT_ITEM_CHEVRON: String = "#E9E9E9"
    public static let DOCTOR_APPOINTMENT_ITEM_ADDRESS_CONTENT: String = "#1B86E4"
    public static let DOCTOR_APPOINTMENT_ITEM_REASON: String = "#BE4A4A"
    public static let DOCTOR_APPOINTMENT_ITEM_ICON_TINT: String = "#DBDBDB"

    // My bookings
    public static let MY_BOOKINGS_HEADER: String = "#1B86E4"
    public static let MY_BOOKINGS_TITLE: String = "#66A8E2"
    public static let MY_BOOKINGS_SUBTITLE: String = "#FFFFFF"
    public static let MY_BOOKINGS_BODY: String = "#E9E9E9"
    public static let MY_BOOKINGS_NO_BOOKING_MSG: String = "#444444"
    public static let MY_BOOKINGS_NO_BOOKING_MSG_TITLE: String = "#FFFFFF"
    public static let MY_BOOKINGS_NO_BOOKING_MSG_CONTENT: String = "#FFFFFF"

    // Shape
    public static let SHAPE_INFO_MSG_BORDER: String = "#1B86E4"
    public static let SHAPE_INFO_MSG_TEXT: String = "#494949"
}

