//
//  Strings.swift
//  DoctoApp
//
//  Created by LAVIOLETTE JOACHIM on 03/12/2019.
//  Copyright © 2019 LAVIOLETTE JOACHIM. All rights reserved.
//

import UIKit

struct Strings {
    public static let APP_NAME: String = "DoctoApp"

    // Titles
    public static let TITLE_SEARCH: String = "Search"
    public static let TITLE_LOGIN: String = "Login"
    public static let TITLE_FORGOT_PASSWORD: String = "Forgot password"
    public static let TITLE_SIGNUP: String = "Sign-up"
    public static let TITLE_MY_PROFILE: String = "My profile"

    // Main
    public static let MAIN_CAPTION: String = "Book an appointment with a specialized doctor online"
    public static let MAIN_SEARCH_BAR_PLACEHOLDER: String = "Doctor, place, speciality..."
    public static let MAIN_SEARCH_BTN: String = "Search"

    // Search

    // Login
    public static let LOGIN_CAPTION: String = "Login and access your profile"
    public static let LOGIN_EMAIL_PLACEHOLDER: String = "Email"
    public static let LOGIN_PWD_PLACEHOLDER: String = "Password"
    public static let LOGIN_STAY_LOGGED: String = "I want to stay connected"
    public static let LOGIN_FORGOT_PWD: String = "Forgot password?"
    public static let LOGIN_BTN: String = "Login"
    public static let LOGIN_MY_PROFILE_BTN: String = "My profile"
    public static let LOGIN_MY_BOOKINGS_BTN: String = "My bookings"
    public static let LOGIN_DELETE_ACCOUNT_BTN: String = "Delete my account"
    public static let LOGIN_LOGOUT_BTN: String = "Logout"
    public static let LOGIN_SIGNUP_CAPTION: String = "Not registered yet?"
    public static let LOGIN_SIGNUP_LINK: String = "Create your account now"
    public static let LOGIN_SIGNUP_PRO_CAPTION: String = "You are a professional?"
    public static let LOGIN_SIGNUP_PRO_LINK: String = "Create your professional account here"
    public static let LOGIN_SUCCESS_MSG_TITLE: String = "Connexion succeeded"
    public static let LOGIN_SUCCESS_MSG_CONTENT: String = "You are now connected. You can view your bookings and update your personal information using the right sidebar."
    public static let LOGIN_ERROR_MSG_TITLE: String = "Connexion failed"
    public static let LOGIN_ERROR_MSG_CONTENT: String = "Impossible to connect. Please check your email and/or your password. Make sure it exists, ask for renewing your password, or create an account using the links below."
    public static let LOGIN_DELETE_ACCOUNT_MSG_TITLE: String = "Account removal failed"
    public static let LOGIN_DELETE_ACCOUNT_MSG_CONTENT: String = "Something went wrong when removing your account.\nPlease contact the admin."
    public static let LOGIN_TOAST_LOGIN_PATIENT_CONTENT: String = "You are now connected to your patient account"
    public static let LOGIN_TOAST_LOGIN_DOCTOR_CONTENT: String = "You are now connected to your doctor account"
    public static let LOGIN_TOAST_LOGOUT_CONTENT: String = "You are now disconnected from your patient account"
    public static let LOGIN_TOAST_USER_REMOVED_CONTENT: String = "Your account was successfully removed."
    public static let LOGIN_DELETE_ACCOUNT_POPUP_CONTENT: String = "If you delete your account, you will not be able to access it anymore. However, the system will keep your data.\nYou still can ask for its removal in which case all your information will be deleted."
    public static let LOGIN_DELETE_ACCOUNT_POPUP_TITLE: String = "Delete your account"
    public static let LOGIN_DELETE_ACCOUNT_POPUP_CLOSE: String = "x"
    public static let LOGIN_DELETE_ACCOUNT_POPUP_DISCARD_BTN_TEXT: String = "Discard"
    public static let LOGIN_DELETE_ACCOUNT_POPUP_CONFIRM_BTN_TEXT: String = "Confirm"

    // Forgot password
    public static let FORGOT_PASSWORD_CAPTION: String = "Reset your password"
    public static let FORGOT_PASSWORD_EMAIL_PLACEHOLDER: String = "Email"
    public static let FORGOT_PASSWORD_PWD_PLACEHOLDER: String = "Password"
    public static let FORGOT_PASSWORD_CONFIRM_PWD_PLACEHOLDER: String = "Confirm your password"
    public static let FORGOT_PASSWORD_BTN: String = "Set new password"
    public static let FORGOT_PASSWORD_SUCCESS_MSG_TITLE: String = "Password successfully reset"
    public static let FORGOT_PASSWORD_SUCCESS_MSG_CONTENT: String = "Your new password is now set. You can use it to login."
    public static let FORGOT_PASSWORD_ERROR_MSG_TITLE: String = "Password not reset"
    public static let FORGOT_PASSWORD_ERROR_MSG_CONTENT: String = "Something went wrong when retrieving your account. Please make sure you provided an existing email address and both given passwords are the same."

    // Signup
    public static let LOGGED_USER_PATIENT_PICTURE = "logged_user_patient_picture_"
    public static let SIGNUP_PICTURE_URI: String = "signup_picture_uri"
    public static let SIGNUP_CAPTION: String = "Sign-up and access your patient profile"
    public static let SIGNUP_TAKE_PICTURE_FROM_CAMERA: String = "Take a picture"
    public static let SIGNUP_SELECT_PICTURE_FROM_GALLERY: String = "Select a picture"
    public static let SIGNUP_LASTNAME: String = "Last name"
    public static let SIGNUP_FIRSTNAME: String = "First name"
    public static let SIGNUP_BIRTHDATE: String = "Birth date"
    public static let SIGNUP_EMAIL: String = "Email"
    public static let SIGNUP_INSURANCE_NUMBER: String = "Insurance number"
    public static let SIGNUP_PWD: String = "Password"
    public static let SIGNUP_CONFIRM_PWD: String = "Confirm your password"
    public static let SIGNUP_STREET1: String = "Street 1"
    public static let SIGNUP_STREET2: String = "Street 2"
    public static let SIGNUP_CITY: String = "City"
    public static let SIGNUP_ZIP: String = "Zip code"
    public static let SIGNUP_COUNTRY: String = "Country"
    public static let SIGNUP_LASTNAME_PLACEHOLDER: String = "Last name"
    public static let SIGNUP_FIRSTNAME_PLACEHOLDER: String = "First name"
    public static let SIGNUP_BIRTHDATE_PLACEHOLDER: String = "Birth date (ie. 1995–05–28)"
    public static let SIGNUP_EMAIL_PLACEHOLDER: String = "Email"
    public static let SIGNUP_INSURANCE_NUMBER_PLACEHOLDER: String = "Insurance number"
    public static let SIGNUP_PWD_PLACEHOLDER: String = "Password"
    public static let SIGNUP_CONFIRM_PWD_PLACEHOLDER: String = "Confirm your password"
    public static let SIGNUP_STREET1_PLACEHOLDER: String = "Street 1"
    public static let SIGNUP_STREET2_PLACEHOLDER: String = "Street 2"
    public static let SIGNUP_CITY_PLACEHOLDER: String = "City"
    public static let SIGNUP_ZIP_PLACEHOLDER: String = "Zip code"
    public static let SIGNUP_COUNTRY_PLACEHOLDER: String = "Country"
    public static let SIGNUP_BTN: String = "sign up"
    public static let SIGNUP_LOGIN_CAPTION: String = "Already have an account?"
    public static let SIGNUP_LOGIN_LINK: String = "Login now"
    public static let SIGNUP_PRO_ACCOUNT_CAPTION: String = "You are a professional?"
    public static let SIGNUP_PRO_ACCOUNT_LINK: String = "Access your professional account"
    public static let SIGNUP_SUCCESS_MSG_TITLE: String = "Registration succeeded"
    public static let SIGNUP_SUCCESS_MSG_CONTENT: String = "You are now registered. You can login to your account using the email you provided to sign-up."
    public static let SIGNUP_ERROR_MSG_TITLE: String = "Registration failed"
    public static let SIGNUP_ERROR_MSG_CONTENT: String = "Impossible to sign-up. Please make sure your email is in a correct format and that all the fields are properly filled. Also check both passwords are corresponding. If your email is already associated to an existing account, login to your account using the link below."
    public static let SIGNUP_TOAST_SIGNUP_CONTENT: String = "You are now registered. Login to your account from the login page."
    public static let SIGNUP_PATIENT_PROFILE_SECTION_LABEL: String = "Profile data"
    public static let SIGNUP_PATIENT_ADDRESS_SECTION_LABEL: String = "Address data"

    // My profile
    public static let MY_PROFILE_PICTURE_URI: String = "my_profile_picture_uri"
    public static let MY_PROFILE_CAPTION: String = "Update your patient profile"
    public static let MY_PROFILE_TAKE_PICTURE_FROM_CAMERA: String = "Take a picture"
    public static let MY_PROFILE_SELECT_PICTURE_FROM_GALLERY: String = "Select a picture"
    public static let MY_PROFILE_LASTNAME: String = "Last name"
    public static let MY_PROFILE_FIRSTNAME: String = "First name"
    public static let MY_PROFILE_BIRTHDATE: String = "Birth date"
    public static let MY_PROFILE_EMAIL: String = "Email"
    public static let MY_PROFILE_INSURANCE_NUMBER: String = "Insurance number"
    public static let MY_PROFILE_OLD_PWD: String = "Old (current) password"
    public static let MY_PROFILE_NEW_PWD: String = "Password"
    public static let MY_PROFILE_CONFIRM_PWD: String = "Confirm your password"
    public static let MY_PROFILE_STREET1: String = "Street 1"
    public static let MY_PROFILE_STREET2: String = "Street 2"
    public static let MY_PROFILE_CITY: String = "City"
    public static let MY_PROFILE_ZIP: String = "Zip code"
    public static let MY_PROFILE_COUNTRY: String = "Country"
    public static let MY_PROFILE_LASTNAME_PLACEHOLDER: String = "Last name"
    public static let MY_PROFILE_FIRSTNAME_PLACEHOLDER: String = "First name"
    public static let MY_PROFILE_BIRTHDATE_PLACEHOLDER: String = "Birth date (ie. 1995–05–28)"
    public static let MY_PROFILE_EMAIL_PLACEHOLDER: String = "Email"
    public static let MY_PROFILE_INSURANCE_NUMBER_PLACEHOLDER: String = "Insurance number"
    public static let MY_PROFILE_OLD_PWD_PLACEHOLDER: String = "Old password"
    public static let MY_PROFILE_NEW_PWD_PLACEHOLDER: String = "New password"
    public static let MY_PROFILE_CONFIRM_PWD_PLACEHOLDER: String = "Confirm your new password"
    public static let MY_PROFILE_STREET1_PLACEHOLDER: String = "Street 1"
    public static let MY_PROFILE_STREET2_PLACEHOLDER: String = "Street 2"
    public static let MY_PROFILE_CITY_PLACEHOLDER: String = "City"
    public static let MY_PROFILE_ZIP_PLACEHOLDER: String = "Zip code"
    public static let MY_PROFILE_COUNTRY_PLACEHOLDER: String = "Country"
    public static let MY_PROFILE_UPDATE_BTN: String = "update my profile"
    public static let MY_PROFILE_SUCCESS_MSG_TITLE: String = "Profile update succeeded"
    public static let MY_PROFILE_SUCCESS_MSG_CONTENT: String = "Your profile has been successfully updated with the provided information. You can anytime change the information of your profile."
    public static let MY_PROFILE_ERROR_MSG_TITLE: String = "Profile update failed"
    public static let MY_PROFILE_ERROR_MSG_CONTENT: String = "Impossible to update your profile. Please make sure your email is in a correct format and that all the fields are properly filled. Also check old password and both new passwords are corresponding, if modified. In case you changed your email address make sure it is available."
    public static let MY_PROFILE_TOAST_UPDATE_CONTENT: String = "Your profile was successfully updated."
    public static let MY_PROFILE_PATIENT_PROFILE_SECTION_LABEL: String = "Profile data"
    public static let MY_PROFILE_PATIENT_ADDRESS_SECTION_LABEL: String = "Address data"

    // Signup pro
    public static let LOGGED_USER_DOCTOR_PICTURE = "logged_user_doctor_picture_"
    public static let LOGGED_USER_DOCTOR_HEADER = "logged_user_doctor_header_"
    public static let SIGNUP_PRO_PICTURE_URI: String = "signup_pro_picture_uri"
    public static let SIGNUP_PRO_CAPTION: String = "Sign-up and access your professional profile"
    public static let SIGNUP_PRO_TAKE_PICTURE_FROM_CAMERA: String = "Take a picture"
    public static let SIGNUP_PRO_SELECT_PICTURE_FROM_GALLERY: String = "Select a picture"
    public static let SIGNUP_PRO_TAKE_HEADER_FROM_CAMERA: String = "Take a header"
    public static let SIGNUP_PRO_SELECT_HEADER_FROM_GALLERY: String = "Select a header"
    public static let SIGNUP_PRO_LASTNAME: String = "Last name"
    public static let SIGNUP_PRO_FIRSTNAME: String = "First name"
    public static let SIGNUP_PRO_SPECIALITY: String = "Speciality"
    public static let SIGNUP_PRO_EMAIL: String = "Email"
    public static let SIGNUP_PRO_DESCRIPTION: String = "Description"
    public static let SIGNUP_PRO_CONTACT_NUMBER: String = "Contact number"
    public static let SIGNUP_PRO_PWD: String = "Password"
    public static let SIGNUP_PRO_CONFIRM_PWD: String = "Confirm your password"
    public static let SIGNUP_PRO_IS_UNDER_AGREEMENT: String = "Are you under agreement?"
    public static let SIGNUP_PRO_IS_HEALTH_INSURANCE_CARD: String = "Do you accept health insurance card?"
    public static let SIGNUP_PRO_IS_THIRD_PARTY_PAYMENT: String = "Do you allow third party payment?"
    public static let SIGNUP_PRO_STREET1: String = "Street 1"
    public static let SIGNUP_PRO_STREET2: String = "Street 2"
    public static let SIGNUP_PRO_CITY: String = "City"
    public static let SIGNUP_PRO_ZIP: String = "Zip code"
    public static let SIGNUP_PRO_COUNTRY: String = "Country"
    public static let SIGNUP_PRO_LASTNAME_PLACEHOLDER: String = "Last name"
    public static let SIGNUP_PRO_FIRSTNAME_PLACEHOLDER: String = "First name"
    public static let SIGNUP_PRO_SPECIALITY_PLACEHOLDER: String = "Speciality"
    public static let SIGNUP_PRO_EMAIL_PLACEHOLDER: String = "Email"
    public static let SIGNUP_PRO_DESCRIPTION_PLACEHOLDER: String = "Description"
    public static let SIGNUP_PRO_CONTACT_NUMBER_PLACEHOLDER: String = "Contact number"
    public static let SIGNUP_PRO_PWD_PLACEHOLDER: String = "Password"
    public static let SIGNUP_PRO_CONFIRM_PWD_PLACEHOLDER: String = "Confirm your password"
    public static let SIGNUP_PRO_STREET1_PLACEHOLDER: String = "Street 1"
    public static let SIGNUP_PRO_STREET2_PLACEHOLDER: String = "Street 2"
    public static let SIGNUP_PRO_CITY_PLACEHOLDER: String = "City"
    public static let SIGNUP_PRO_ZIP_PLACEHOLDER: String = "Zip code"
    public static let SIGNUP_PRO_COUNTRY_PLACEHOLDER: String = "Country"
    public static let SIGNUP_PRO_AVAILABILITY_INFO: String = "Warning about time.\nMust be in 24h format."
    public static let SIGNUP_PRO_AVAILABILITY_INPUT_PLACEHOLDER: String = "ie. 15:00"
    public static let SIGNUP_PRO_AVAILABILITY_ERROR: String = "An error occurred when adding the availability.\nPlease check the fields.\nMake sure you have not already added it."
    public static let SIGNUP_PRO_REASON_DESCRIPTION_INPUT_PLACEHOLDER: String = "ie. I am depressed"
    public static let SIGNUP_PRO_REASON_ERROR: String = "An error occurred when adding the reason.\nPlease make sure you have not already added it."
    public static let SIGNUP_PRO_EXPERIENCE_YEAR_INPUT_PLACEHOLDER: String = "ie. 2009"
    public static let SIGNUP_PRO_EXPERIENCE_DESCRIPTION_INPUT_PLACEHOLDER: String = "ie. 3 years in a Paris Hospital"
    public static let SIGNUP_PRO_EXPERIENCE_ERROR: String = "An error occurred when adding the experience.\nPlease check the fields.\nMake sure you have not already added it."
    public static let SIGNUP_PRO_TRAINING_YEAR_INPUT_PLACEHOLDER: String = "ie. 2013"
    public static let SIGNUP_PRO_TRAINING_DESCRIPTION_INPUT_PLACEHOLDER: String = "ie. MSc in Medicine and Psychology"
    public static let SIGNUP_PRO_TRAINING_ERROR: String = "An error occurred when adding the training.\nPlease check the fields.\nMake sure you have not already added it."
    public static let SIGNUP_PRO_LANGUAGE_ERROR: String = "An error occurred when adding the language.\nPlease make sure you have not already added it."
    public static let SIGNUP_PRO_PAYMENT_OPTION_ERROR: String = "An error occurred when adding the payment option.\nPlease make sure you have not already added it."
    public static let SIGNUP_PRO_BTN: String = "sign up"
    public static let SIGNUP_PRO_LOGIN_CAPTION: String = "Already have an account?"
    public static let SIGNUP_PRO_LOGIN_LINK: String = "Login now"
    public static let SIGNUP_PRO_PRIVATE_ACCOUNT_CAPTION: String = "You are a private?"
    public static let SIGNUP_PRO_PRIVATE_ACCOUNT_LINK: String = "Access your patient account"
    public static let SIGNUP_PRO_SUCCESS_MSG_TITLE: String = "Registration succeeded"
    public static let SIGNUP_PRO_SUCCESS_MSG_CONTENT: String = "You are now registered. You can login to your account using the email you provided to sign-up."
    public static let SIGNUP_PRO_ERROR_MSG_TITLE: String = "Registration failed"
    public static let SIGNUP_PRO_ERROR_MSG_CONTENT: String = "Impossible to sign-up. Please make sure your email is in a correct format and that all the fields are properly filled. Also check both passwords are corresponding. If your email is already associated to an existing account, login to your account using the link below."
    public static let SIGNUP_PRO_TOAST_SIGNUP_CONTENT: String = "You are now registered. Login to your account from the login page."
    public static let SIGNUP_PRO_DOCTOR_PROFILE_SECTION_LABEL: String = "Profile data"
    public static let SIGNUP_PRO_DOCTOR_ADDRESS_SECTION_LABEL: String = "Address data"
    public static let SIGNUP_PRO_DOCTOR_PRICES_REFUNDS_SECTION_LABEL: String = "Prices and refunds options"
    public static let SIGNUP_PRO_DOCTOR_AVAILABILITIES_SECTION_LABEL: String = "Availabilities"
    public static let SIGNUP_PRO_DOCTOR_REASON_SECTION_LABEL: String = "Consultation reasons"
    public static let SIGNUP_PRO_DOCTOR_EXPERIENCE_SECTION_LABEL: String = "Experience"
    public static let SIGNUP_PRO_DOCTOR_EDUCATION_SECTION_LABEL: String = "Education"
    public static let SIGNUP_PRO_DOCTOR_LANGUAGES_SECTION_LABEL: String = "Spoken languages"
    public static let SIGNUP_PRO_DOCTOR_PAYMENT_OPTIONS_SECTION_LABEL: String = "Allowed payment options"
    public static let SIGNUP_PRO_ADD_AVAILABILITY_BTN_TEXT: String = "Add availability"
    public static let SIGNUP_PRO_ADD_REASON_BTN_TEXT: String = "Add reason"
    public static let SIGNUP_PRO_ADD_TRAINING_BTN_TEXT: String = "Add training"
    public static let SIGNUP_PRO_ADD_EXPERIENCE_BTN_TEXT: String = "Add experience"
    public static let SIGNUP_PRO_ADD_LANGUAGE_BTN_TEXT: String = "Add language"
    public static let SIGNUP_PRO_ADD_PAYMENT_OPTION_BTN_TEXT: String = "Add payment option"
    public static let SIGNUP_PRO_TOAST_ADD_AVAILABILITY_CONTENT: String = "Availability successfully added."
    public static let SIGNUP_PRO_TOAST_ADD_REASON_CONTENT: String = "Reason successfully added."
    public static let SIGNUP_PRO_TOAST_ADD_EXPERIENCE_CONTENT: String = "Experience successfully added."
    public static let SIGNUP_PRO_TOAST_ADD_TRAINING_CONTENT: String = "Training successfully added."
    public static let SIGNUP_PRO_TOAST_ADD_LANGUAGE_CONTENT: String = "Language successfully added."
    public static let SIGNUP_PRO_TOAST_ADD_PAYMENT_OPTION_CONTENT: String = "Payment option successfully added."
    public static let SIGNUP_PRO_TOAST_REMOVE_AVAILABILITY_CONTENT: String = "Availability successfully removed."
    public static let SIGNUP_PRO_TOAST_REMOVE_REASON_CONTENT: String = "Reason successfully removed."
    public static let SIGNUP_PRO_TOAST_REMOVE_EXPERIENCE_CONTENT: String = "Experience successfully removed."
    public static let SIGNUP_PRO_TOAST_REMOVE_TRAINING_CONTENT: String = "Training successfully removed."
    public static let SIGNUP_PRO_TOAST_REMOVE_LANGUAGE_CONTENT: String = "Language successfully removed."
    public static let SIGNUP_PRO_TOAST_REMOVE_PAYMENT_OPTION_CONTENT: String = "Payment option successfully removed."
    public static let SIGNUP_PRO_DAYS_PLACEHOLDER: String = "Choose a day"

    // Signup list item
    public static let SIGNUP_PRO_LIST_ITEM_PIPE: String = "|"

    // Availability signup list item
    public static let AVAILABILITY_SIGNUP_PRO_LIST_ITEM_DAY: String = "{day}"
    public static let AVAILABILITY_SIGNUP_PRO_LIST_ITEM_TIME: String = "[time}"

    // Reason signup list item
    public static let REASON_SIGNUP_PRO_LIST_ITEM_DESCRIPTION: String = "{description}"

    // Education signup list item
    public static let EDUCATION_SIGNUP_PRO_LIST_ITEM_YEAR: String = "[year}"
    public static let EDUCATION_SIGNUP_PRO_LIST_ITEM_DEGREE: String = "{degree}"

    // Experience signup list item
    public static let EXPERIENCE_SIGNUP_PRO_LIST_ITEM_YEAR: String = "{year}"
    public static let EXPERIENCE_SIGNUP_PRO_LIST_ITEM_DESCRIPTION: String = "{description}"

    // Language signup list item
    public static let LANGUAGE_SIGNUP_PRO_LIST_ITEM_DESCRIPTION: String = "{description}"

    // Payment option signup list item
    public static let PAYMENT_OPTION_SIGNUP_PRO_LIST_ITEM_DESCRIPTION: String = "{description}"

    // My profile pro
    public static let MY_PROFILE_PRO_PICTURE_URI: String = "my_profile_pro_picture_uri"
    public static let MY_PROFILE_PRO_CAPTION: String = "Update your professional profile"
    public static let MY_PROFILE_PRO_TAKE_PICTURE_FROM_CAMERA: String = "Take a picture"
    public static let MY_PROFILE_PRO_SELECT_PICTURE_FROM_GALLERY: String = "Select a picture"
    public static let MY_PROFILE_PRO_TAKE_HEADER_FROM_CAMERA: String = "Take a header"
    public static let MY_PROFILE_PRO_SELECT_HEADER_FROM_GALLERY: String = "Select a header"
    public static let MY_PROFILE_PRO_LASTNAME: String = "Last name"
    public static let MY_PROFILE_PRO_FIRSTNAME: String = "First name"
    public static let MY_PROFILE_PRO_SPECIALITY: String = "Speciality"
    public static let MY_PROFILE_PRO_EMAIL: String = "Email"
    public static let MY_PROFILE_PRO_DESCRIPTION: String = "Description"
    public static let MY_PROFILE_PRO_CONTACT_NUMBER: String = "Contact number"
    public static let MY_PROFILE_PRO_PWD: String = "Password"
    public static let MY_PROFILE_PRO_CONFIRM_PWD: String = "Confirm your password"
    public static let MY_PROFILE_PRO_IS_UNDER_AGREEMENT: String = "Are you under agreement?"
    public static let MY_PROFILE_PRO_IS_HEALTH_INSURANCE_CARD: String = "Do you accept health insurance card?"
    public static let MY_PROFILE_PRO_IS_THIRD_PARTY_PAYMENT: String = "Do you allow third party payment?"
    public static let MY_PROFILE_PRO_STREET1: String = "Street 1"
    public static let MY_PROFILE_PRO_STREET2: String = "Street 2"
    public static let MY_PROFILE_PRO_CITY: String = "City"
    public static let MY_PROFILE_PRO_ZIP: String = "Zip code"
    public static let MY_PROFILE_PRO_COUNTRY: String = "Country"
    public static let MY_PROFILE_PRO_LASTNAME_PLACEHOLDER: String = "Last name"
    public static let MY_PROFILE_PRO_FIRSTNAME_PLACEHOLDER: String = "First name"
    public static let MY_PROFILE_PRO_SPECIALITY_PLACEHOLDER: String = "Speciality"
    public static let MY_PROFILE_PRO_EMAIL_PLACEHOLDER: String = "Email"
    public static let MY_PROFILE_PRO_DESCRIPTION_PLACEHOLDER: String = "Description"
    public static let MY_PROFILE_PRO_CONTACT_NUMBER_PLACEHOLDER: String = "Contact number"
    public static let MY_PROFILE_PRO_OLD_PWD_PLACEHOLDER: String = "Old password"
    public static let MY_PROFILE_PRO_NEW_PWD_PLACEHOLDER: String = "New password"
    public static let MY_PROFILE_PRO_CONFIRM_PWD_PLACEHOLDER: String = "Confirm your password"
    public static let MY_PROFILE_PRO_STREET1_PLACEHOLDER: String = "Street 1"
    public static let MY_PROFILE_PRO_STREET2_PLACEHOLDER: String = "Street 2"
    public static let MY_PROFILE_PRO_CITY_PLACEHOLDER: String = "City"
    public static let MY_PROFILE_PRO_ZIP_PLACEHOLDER: String = "Zip code"
    public static let MY_PROFILE_PRO_COUNTRY_PLACEHOLDER: String = "Country"
    public static let MY_PROFILE_PRO_AVAILABILITY_INFO: String = "Warning about time.\nMust be in 24h format."
    public static let MY_PROFILE_PRO_AVAILABILITY_INPUT_PLACEHOLDER: String = "ie. 15:00"
    public static let MY_PROFILE_PRO_AVAILABILITY_ERROR: String = "An error occurred when adding the availability.\nPlease check the fields.\nMake sure you have not already added it."
    public static let MY_PROFILE_PRO_REASON_DESCRIPTION_INPUT_PLACEHOLDER: String = "ie. I am depressed"
    public static let MY_PROFILE_PRO_REASON_ERROR: String = "An error occurred when adding the reason.\nPlease make sure you have not already added it."
    public static let MY_PROFILE_PRO_EXPERIENCE_YEAR_INPUT_PLACEHOLDER: String = "ie. 2009"
    public static let MY_PROFILE_PRO_EXPERIENCE_DESCRIPTION_INPUT_PLACEHOLDER: String = "ie. 3 years in a Paris Hospital"
    public static let MY_PROFILE_PRO_EXPERIENCE_ERROR: String = "An error occurred when adding the experience.\nPlease check the fields.\nMake sure you have not already added it."
    public static let MY_PROFILE_PRO_TRAINING_YEAR_INPUT_PLACEHOLDER: String = "ie. 2013"
    public static let MY_PROFILE_PRO_TRAINING_DESCRIPTION_INPUT_PLACEHOLDER: String = "ie. MSc in Medicine and Psychology"
    public static let MY_PROFILE_PRO_TRAINING_ERROR: String = "An error occurred when adding the training.\nPlease check the fields.\nMake sure you have not already added it."
    public static let MY_PROFILE_PRO_LANGUAGE_ERROR: String = "An error occurred when adding the language.\nPlease make sure you have not already added it."
    public static let MY_PROFILE_PRO_PAYMENT_OPTION_ERROR: String = "An error occurred when adding the payment option.\nPlease make sure you have not already added it."
    public static let MY_PROFILE_PRO_UPDATE_BTN: String = "Update my profile"
    public static let MY_PROFILE_PRO_SUCCESS_MSG_TITLE: String = "Update succeeded"
    public static let MY_PROFILE_PRO_SUCCESS_MSG_CONTENT: String = "Your professional profile has been successfully updated with the provided information. You can anytime change the information of your profile."
    public static let MY_PROFILE_PRO_ERROR_MSG_TITLE: String = "Update failed"
    public static let MY_PROFILE_PRO_ERROR_MSG_CONTENT: String = "Impossible to update your profile. Please make sure your email is in a correct format and that all the fields are properly filled. Also check old password and both new passwords are corresponding, if modified. In case you changed your email address make sure it is available."
    public static let MY_PROFILE_PRO_TOAST_UPDATE_CONTENT: String = "Your professional profile was successfully updated."
    public static let MY_PROFILE_PRO_DOCTOR_PROFILE_SECTION_LABEL: String = "Profile data"
    public static let MY_PROFILE_PRO_DOCTOR_ADDRESS_SECTION_LABEL: String = "Address data"
    public static let MY_PROFILE_PRO_DOCTOR_PRICES_REFUNDS_SECTION_LABEL: String = "Prices and refunds options"
    public static let MY_PROFILE_PRO_DOCTOR_AVAILABILITIES_SECTION_LABEL: String = "Availabilities"
    public static let MY_PROFILE_PRO_DOCTOR_REASON_SECTION_LABEL: String = "Consultation reasons"
    public static let MY_PROFILE_PRO_DOCTOR_EXPERIENCE_SECTION_LABEL: String = "Experience"
    public static let MY_PROFILE_PRO_DOCTOR_EDUCATION_SECTION_LABEL: String = "Education"
    public static let MY_PROFILE_PRO_DOCTOR_LANGUAGES_SECTION_LABEL: String = "Spoken languages"
    public static let MY_PROFILE_PRO_DOCTOR_PAYMENT_OPTIONS_SECTION_LABEL: String = "Allowed payment options"
    public static let MY_PROFILE_PRO_ADD_AVAILABILITY_BTN_TEXT: String = "Add availability"
    public static let MY_PROFILE_PRO_ADD_REASON_BTN_TEXT: String = "Add reason"
    public static let MY_PROFILE_PRO_ADD_TRAINING_BTN_TEXT: String = "Add training"
    public static let MY_PROFILE_PRO_ADD_EXPERIENCE_BTN_TEXT: String = "Add experience"
    public static let MY_PROFILE_PRO_ADD_LANGUAGE_BTN_TEXT: String = "Add language"
    public static let MY_PROFILE_PRO_ADD_PAYMENT_OPTION_BTN_TEXT: String = "Add payment option"
    public static let MY_PROFILE_PRO_TOAST_ADD_AVAILABILITY_CONTENT: String = "Availability successfully added."
    public static let MY_PROFILE_PRO_TOAST_ADD_REASON_CONTENT: String = "Reason successfully added."
    public static let MY_PROFILE_PRO_TOAST_ADD_EXPERIENCE_CONTENT: String = "Experience successfully added."
    public static let MY_PROFILE_PRO_TOAST_ADD_TRAINING_CONTENT: String = "Training successfully added."
    public static let MY_PROFILE_PRO_TOAST_ADD_LANGUAGE_CONTENT: String = "Language successfully added."
    public static let MY_PROFILE_PRO_TOAST_ADD_PAYMENT_OPTION_CONTENT: String = "Payment option successfully added."
    public static let MY_PROFILE_PRO_TOAST_REMOVE_AVAILABILITY_CONTENT: String = "Availability successfully removed."
    public static let MY_PROFILE_PRO_TOAST_REMOVE_REASON_CONTENT: String = "Reason successfully removed."
    public static let MY_PROFILE_PRO_TOAST_REMOVE_EXPERIENCE_CONTENT: String = "Experience successfully removed."
    public static let MY_PROFILE_PRO_TOAST_REMOVE_TRAINING_CONTENT: String = "Training successfully removed."
    public static let MY_PROFILE_PRO_TOAST_REMOVE_LANGUAGE_CONTENT: String = "Language successfully removed."
    public static let MY_PROFILE_PRO_TOAST_REMOVE_PAYMENT_OPTION_CONTENT: String = "Payment option successfully removed."
    public static let MY_PROFILE_PRO_DAYS_PLACEHOLDER: String = "Choose a day"

    // My profile pro list item
    public static let MY_PROFILE_PRO_LIST_ITEM_PIPE: String = "|"

    // Availability my profile pro list item
    public static let AVAILABILITY_MY_PROFILE_PRO_LIST_ITEM_DAY: String = "{day}"
    public static let AVAILABILITY_MY_PROFILE_PRO_LIST_ITEM_TIME: String = "[time}"

    // Reason my profile pro list item
    public static let REASON_MY_PROFILE_PRO_LIST_ITEM_DESCRIPTION: String = "{description}"

    // Education my profile pro list item
    public static let EDUCATION_MY_PROFILE_PRO_LIST_ITEM_YEAR: String = "[year}"
    public static let EDUCATION_MY_PROFILE_PRO_LIST_ITEM_DEGREE: String = "{degree}"

    // Experience my profile pro list item
    public static let EXPERIENCE_MY_PROFILE_PRO_LIST_ITEM_YEAR: String = "{year}"
    public static let EXPERIENCE_MY_PROFILE_PRO_LIST_ITEM_DESCRIPTION: String = "{description}"

    // Language my profile pro list item
    public static let LANGUAGE_MY_PROFILE_PRO_LIST_ITEM_DESCRIPTION: String = "{description}"

    // Payment option my profile pro list item
    public static let PAYMENT_OPTION_MY_PROFILE_PRO_LIST_ITEM_DESCRIPTION: String = "{description}"

    // Search
    public static let SEARCH_BAR_PLACEHOLDER: String = "Doctor, place, speciality..."
    public static let SEARCH_BTN: String = "Search"
    public static let SEARCH_LIST_ITEM_CHEVRON: String = ">"
    public static let SEARCH_LIST_ITEM_CHEVRON_LABEL: String = "search_list_item_chevron"

    // Search list
    public static let DOCTOR_SERVICE_DOCTOR_PICTURE: String = "search_list_item_doctor_picture"
    public static let DOCTOR_SERVICE_DOCTOR_FULLNAME: String = "search_list_item_doctor_fullname"
    public static let DOCTOR_SERVICE_DOCTOR_SPECIALITY: String = "search_list_item_doctor_speciality"
    public static let DOCTOR_SERVICE_DOCTOR_ADDRESS: String = "search_list_item_doctor_address"
    public static let DOCTOR_SERVICE_DOCTOR_PRICES_REFUNDS: String = "search_list_item_doctor_prices__refunds"
    public static let DOCTOR_SERVICE_DOCTOR_PAYMENT_OPTIONS: String = "search_list_item_doctor_payment_options"
    public static let DOCTOR_SERVICE_DOCTOR_DESCRIPTION: String = "search_list_item_doctor_description"
    public static let DOCTOR_SERVICE_DOCTOR_HOURS_CONTACTS: String = "search_list_item_doctor_hours_contacts"
    public static let DOCTOR_SERVICE_DOCTOR_EDUCATION: String = "search_list_item_doctor_education"
    public static let DOCTOR_SERVICE_DOCTOR_LANGUAGES: String = "search_list_item_doctor_languages"
    public static let DOCTOR_SERVICE_DOCTOR_EXPERIENCES: String = "search_list_item_doctor_experiences"

    // Reason list
    public static let DOCTOR_SERVICE_DOCTOR_REASON: String = "reason_list_item_reason"

    // Doctor profile
    public static let DOCTOR_PROFILE_BOOK_APPOINTMENT: String = "Book an appointment online"
    public static let DOCTOR_PROFILE_FULLNAME: String = "{doctor_fullname}"
    public static let DOCTOR_PROFILE_ADDRESS: String = "Address"
    public static let DOCTOR_PROFILE_PRICES_REFUNDS: String = "Prices and refunds"
    public static let DOCTOR_PROFILE_IS_UNDER_AGREEMENT_TRUE: String = "Under agreement"
    public static let DOCTOR_PROFILE_IS_UNDER_AGREEMENT_FALSE: String = "Not under agreement"
    public static let DOCTOR_PROFILE_IS_HEALTH_INSURANCE_CARD_TRUE: String = "Accepts health insurance card"
    public static let DOCTOR_PROFILE_IS_HEALTH_INSURANCE_CARD_FALSE: String = "Does not accept health insurance card"
    public static let DOCTOR_PROFILE_IS_THIRD_PARTY_PAYMENT_TRUE: String = "Third party payment: Social welfare and complementary health insurance"
    public static let DOCTOR_PROFILE_PAYMENT_OPTIONS: String = "Payment options"
    public static let DOCTOR_PROFILE_DESCRIPTION: String = "Description"
    public static let DOCTOR_PROFILE_HOURS_CONTACTS: String = "Hours and contacts"
    public static let DOCTOR_PROFILE_EDUCATION: String = "Education"
    public static let DOCTOR_PROFILE_LANGUAGES: String = "Spoken languages"
    public static let DOCTOR_PROFILE_EXPERIENCES: String = "Experiences"
    public static let DOCTOR_PROFILE_SECTION_EXPAND: String = "+"
    public static let DOCTOR_PROFILE_POPUP_CONTENT: String = "{popup_content}"
    public static let DOCTOR_PROFILE_POPUP_TITLE: String = "{popup_title}"
    public static let DOCTOR_PROFILE_POPUP_CLOSE: String = "x"
    public static let DOCTOR_PROFILE_POPUP_IS_UNDER_AGREEMENT: String = "Area and agreement"
    public static let DOCTOR_PROFILE_POPUP_IS_UNDER_AGREEMENT_CONTENT: String = "This doctor is under agreement. It applies basic rates for routine care for which you will be refunded by social welfare. The rest can be supported partially or entirely by your complementary mutual health."
    public static let DOCTOR_PROFILE_POPUP_IS_THIRD_PARTY_PAYMENT: String = "Third party payment"
    public static let DOCTOR_PROFILE_POPUP_IS_THIRD_PARTY_PAYMENT_CONTENT: String = "You will not have to advance the social welfare and complementary health insurance costs.\nTo allow third party payment, please be sure to update your health insurance card. Also do not forget your complementary health insurance card.\nExample : for a simple consultation with a generalist practitioner at 25€ you will only have to pay the 1€ of flat rate participation."
    public static let DOCTOR_PROFILE_POPUP_IS_HEALTH_INSURANCE_CARD: String = "Insurance card"
    public static let DOCTOR_PROFILE_POPUP_IS_HEALTH_INSURANCE_CARD_CONTENT: String = "Make sure your health insurance card is up to date in order to benefit from remote transmission and be refunded quickly. If it is not, update it from a pharmacy kiosk.\nRemote transmission prevents you from sending care sheet."

    // Choose reason
    public static let CHOOSE_REASON_TITLE_1: String = "Book an appointment"
    public static let CHOOSE_REASON_DOCTOR_FULLNAME: String = "{doctor_fullname}"
    public static let CHOOSE_REASON_TITLE_2: String = "Choose your consultation\'s reason"
    public static let CHOOSE_REASON_DR: String = "Dr"

    // Choose datetime
    public static let CHOOSE_DATE_TIME_TITLE_1: String = "Book an appointment"
    public static let CHOOSE_DATE_TIME_DOCTOR_FULLNAME: String = "{doctor_fullname}"
    public static let CHOOSE_DATE_TIME_TITLE_2: String = "Choose your consultation\'s date"
    public static let CHOOSE_DATE_TIME_DR: String = "Dr"
    public static let DATE_TIME_DAY_CONTENT: String = "{Day, Month Number}"
    public static let DATE_TIME_TIME_CONTENT: String = "{hh:mm}"
    public static let CHOOSE_DATE_TIME_TOAST_BOOKING_UPDATED_SUCCESS: String = "Your booking was successfully updated"
    public static let CHOOSE_DATE_TIME_TOAST_BOOKING_UPDATED_ERROR: String = "Something went wrong when updating your booking"

    // Date service
    public static let DATE_SERVICE_TIME: String = "time"
    public static let DATE_SERVICE_DAY_NAME: String = "day_name"
    public static let DATE_SERVICE_DAY_NUMBER: String = "day_number"
    public static let DATE_SERVICE_MONTH_NAME: String = "month_name"
    public static let DATE_SERVICE_YEAR: String = "year"
    public static let DATE_SERVICE_MONTH_NUMBER: String = "month_number"
    public static let DATE_SERVICE_TAG: String = "_tag_{time}_{day_name}_{day_number}_{month_name}"
    public static let DATE_SERVICE_FULL_DATE: String = "{day_name}, {month_name} {day_number}"
    public static let DATE_SERVICE_DATE: String = "{year}-{month_number}-{day_number}"

    // Confirm appointment
    public static let CONFIRM_APPOINTMENT_HEADER_TITLE: String = "Booking summary"
    public static let CONFIRM_APPOINTMENT_SUCCESS_MSG_TITLE: String = "Your booking is confirmed"
    public static let CONFIRM_APPOINTMENT_SUCCESS_MSG_CONTENT: String = "We just sent you a confirmation email for your appointment. You will also receive an SMS the day before your appointment."
    public static let CONFIRM_APPOINTMENT_ERROR_MSG_TITLE: String = "Something went wrong with your booking…"
    public static let CONFIRM_APPOINTMENT_ERROR_MSG_CONTENT: String = "Your booking could not be confirmed. It appears you already have a booking scheduled at this date with the doctor."
    public static let CONFIRM_APPOINTMENT_SEE_MY_BOOKINGS: String = "See my bookings"

    // Appointment summary
    public static let APPOINTMENT_SUMMARY_FULLDAY: String = "{Day, Month X}"
    public static let APPOINTMENT_SUMMARY_TIME: String = "{hh:mm}"
    public static let APPOINTMENT_SUMMARY_DOCTOR_FULLNAME: String = "{doctor_fullname}"
    public static let APPOINTMENT_SUMMARY_DOCTOR_SPECIALITY: String = "{doctor_speciality}"
    public static let APPOINTMENT_SUMMARY_CHEVRON: String = ">"
    public static let APPOINTMENT_SUMMARY_REASON: String = "{reason}"
    public static let APPOINTMENT_SUMMARY_PATIENT_TITLE: String = "Patient"
    public static let APPOINTMENT_SUMMARY_PATIENT_FULLNAME: String = "{patient_fullname}"
    public static let APPOINTMENT_SUMMARY_WARNING_MSG_TITLE: String = "Important message to read before your appointment"
    public static let APPOINTMENT_SUMMARY_WARNING_MSG_CONTENT: String = "{warning_msg}"
    public static let APPOINTMENT_SUMMARY_WARNING_MSG_THIRD_PARTY_PAYMENT_FALSE: String = "No third party payment.\nYou pay the consultation costs in the whole and handle their refunding by yourself."
    public static let APPOINTMENT_SUMMARY_WARNING_MSG_THIRD_PARTY_PAYMENT_TRUE: String = "Third party payment allowed."
    public static let APPOINTMENT_SUMMARY_CONTACT_NUMBER: String = "{doctor_contact_number}"
    public static let APPOINTMENT_SUMMARY_ADDRESS_CONTENT: String = "{doctor_address_content}"
    public static let APPOINTMENT_SUMMARY_PAYMENT_OPTIONS_TITLE: String = "Payment options"
    public static let APPOINTMENT_SUMMARY_PAYMENT_OPTIONS_CONTENT: String = "{doctor_payment_options}"
    public static let APPOINTMENT_SUMMARY_PRICES_REFUNDS_TITLE: String = "Prices and refunds"
    public static let APPOINTMENT_SUMMARY_PRICES_REFUNDS_CONTENT: String = "{doctor_prices_refunds}"

    // Patient appointment item
    public static let PATIENT_APPOINTMENT_ITEM_FULLDAY: String = "{Day, Month X}"
    public static let PATIENT_APPOINTMENT_ITEM_TIME: String = "{hh:mm}"
    public static let PATIENT_APPOINTMENT_ITEM_DOCTOR_FULLNAME: String = "{doctor_fullname}"
    public static let PATIENT_APPOINTMENT_ITEM_DOCTOR_SPECIALITY: String = "{doctor_speciality}"
    public static let PATIENT_APPOINTMENT_ITEM_UPDATE_APPOINTMENT: String = "Update appointment"
    public static let PATIENT_APPOINTMENT_ITEM_CANCEL_APPOINTMENT: String = "Cancel appointment"
    public static let PATIENT_APPOINTMENT_ITEM_CHEVRON: String = ">"

    // Show booking
    public static let SHOW_BOOKING_TITLE: String = "Booking - Appointment"
    public static let SHOW_BOOKING_SUBTITLE: String = "Booking details"
    public static let SHOW_BOOKING_APPOINTMENT_FULLDAY: String = "{Day, Month X}"
    public static let SHOW_BOOKING_APPOINTMENT_TIME: String = "{hh:mm}"
    public static let SHOW_BOOKING_APPOINTMENT_DOCTOR_FULLNAME: String = "{doctor_fullname}"
    public static let SHOW_BOOKING_APPOINTMENT_DOCTOR_SPECIALITY: String = "{doctor_speciality}"
    public static let SHOW_BOOKING_APPOINTMENT_PATIENT_FULLNAME: String = "{patient_fullname}"
    public static let SHOW_BOOKING_APPOINTMENT_PATIENT_BIRTHDATE: String = "Born on the {patient_birthdate}"
    public static let SHOW_BOOKING_APPOINTMENT_PATIENT_BIRTHDATE_PREFIX: String = "Born on the "
    public static let SHOW_BOOKING_APPOINTMENT_UPDATE_APPOINTMENT: String = "Update appointment"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT: String = "Cancel appointment"
    public static let SHOW_BOOKING_APPOINTMENT_CHEVRON: String = ">"
    public static let SHOW_BOOKING_APPOINTMENT_REASON: String = "{reason}"
    public static let SHOW_BOOKING_APPOINTMENT_WARNING_MSG_TITLE: String = "Important message to read before your appointment"
    public static let SHOW_BOOKING_APPOINTMENT_WARNING_MSG_CONTENT: String = "{warning_msg}"
    public static let SHOW_BOOKING_APPOINTMENT_WARNING_MSG_THIRD_PARTY_PAYMENT_FALSE: String = "No third party payment.\nYou pay the consultation costs in the whole and handle their refunding by yourself."
    public static let SHOW_BOOKING_APPOINTMENT_WARNING_MSG_THIRD_PARTY_PAYMENT_TRUE: String = "Third party payment allowed."
    public static let SHOW_BOOKING_APPOINTMENT_CONTACT_NUMBER: String = "{doctor_contact_number}"
    public static let SHOW_BOOKING_APPOINTMENT_ADDRESS_CONTENT: String = "{doctor_address_content}"
    public static let SHOW_BOOKING_APPOINTMENT_PAYMENT_OPTIONS_TITLE: String = "Payment options"
    public static let SHOW_BOOKING_APPOINTMENT_PAYMENT_OPTIONS_CONTENT: String = "{doctor_payment_options}"
    public static let SHOW_BOOKING_APPOINTMENT_PRICES_REFUNDS_TITLE: String = "Prices and refunds"
    public static let SHOW_BOOKING_APPOINTMENT_PRICES_REFUNDS_CONTENT: String = "{doctor_prices_refunds}"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_CONTENT_1: String = "Do you want to cancel the following appointment?"
    public static let SHOW_BOOKING_CANCEL_BOOKING_POPUP_CONTENT_BOOKING_FULLDATE: String = "{booking_fulldate}"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_CONTENT_APPOINTMENT_DATE_PREFIX: String = "on "
    public static let SHOW_BOOKING_CANCEL_BOOKING_POPUP_CONTENT_BOOKING_TIME: String = "{booking_time}"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_CONTENT_APPOINTMENT_TIME_PREFIX: String = "at "
    public static let SHOW_BOOKING_CANCEL_BOOKING_POPUP_CONTENT_DOCTOR_FULLNAME: String = "{doctor_fullname}"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_CONTENT_DOCTOR_FULLNAME_PREFIX: String = "with Dr "
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_TITLE: String = "Cancel your appointment"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_CLOSE: String = "x"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_DISCARD_BTN_TEXT: String = "Discard"
    public static let SHOW_BOOKING_APPOINTMENT_CANCEL_APPOINTMENT_POPUP_CONFIRM_BTN_TEXT: String = "Confirm cancellation"
    public static let SHOW_BOOKING_TOAST_BOOKING_CANCELLED_SUCCESS_CONTENT: String = "Booking successfully cancelled."
    public static let SHOW_BOOKING_TOAST_BOOKING_CANCELLED_FAIL_CONTENT: String = "Something went wrong when cancelling the booking. Please retry."
    public static let SHOW_BOOKING_TOAST_BOOKING_UPDATED_SUCCESS_CONTENT: String = "Booking successfully updated."
    public static let SHOW_BOOKING_TOAST_BOOKING_UPDATED_FAIL_CONTENT: String = "Something went wrong when updating the booking. Please retry."

    // Doctor appointment item
    public static let DOCTOR_APPOINTMENT_ITEM_FULLDAY: String = "{Day, Month X}"
    public static let DOCTOR_APPOINTMENT_ITEM_TIME: String = "{hh:mm}"
    public static let DOCTOR_APPOINTMENT_ITEM_PATIENT_FULLNAME: String = "{patient_fullname}"
    public static let DOCTOR_APPOINTMENT_ITEM_PATIENT_BIRTHDATE: String = "Born on the {patient_birthdate}"
    public static let DOCTOR_APPOINTMENT_ITEM_PATIENT_BIRTHDATE_PREFIX: String = "Born on the "
    public static let DOCTOR_APPOINTMENT_ITEM_CHEVRON: String = ">"
    public static let DOCTOR_APPOINTMENT_ITEM_REASON: String = "{reason}"
    public static let DOCTOR_APPOINTMENT_ITEM_ADDRESS_CONTENT: String = "{patient_address_content}"

    // My bookings
    public static let MY_BOOKINGS_TITLE_PATIENT: String = "My bookings"
    public static let MY_BOOKINGS_TITLE_DOCTOR: String = "My appointments"
    public static let MY_BOOKINGS_SUBTITLE: String = "See all the appointments"
    public static let MY_BOOKINGS_NO_BOOKING_MSG_TITLE: String = "No booking to display"
    public static let MY_BOOKINGS_NO_BOOKING_MSG_CONTENT: String = "It appears you have no booking registered yet in the system.\nTo book an appointment with a doctor, use the search system from the main screen of the app."
    public static let DOCTOR_PROFILE_SPECIALITY: String = "{doctor_speciality}"
    public static let REQUEST_CODE: String = "request_code"
    
    // User data
    public static let USER_ID_KEY: String = "user_id"
    public static let USER_TYPE_KEY: String = "user_type"
    public static let USER_TYPE_PATIENT: String = "Patient"
    public static let USER_TYPE_DOCTOR: String = "Doctor"
}

